title: Gabriel Madigan # your name (or website title) here
logo: "/images/GabrielMadiganProfilePicture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Data scientist and former CERN particle physicist with a passion for data exploration and model building. PhD in physics form Northeastern University.
  <br><br>
  <a href="https://www.linkedin.com/in/gabrielmadigan/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-YGEBZFD2F1 # your Google Analytics tracking ID here
